version: '2'
services:
  jupyter:
    image: "iganbold/jupyter"
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/srv/notebooks/
    command: sh -c 'jupyter notebook --ip 0.0.0.0 --port=8888 --no-browser'
